using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Mnemotron.Data.ClickHouse.ADO.Parameters;
using Mnemotron.Data.ClickHouse.ADO.Readers;
using Mnemotron.Data.ClickHouse.Diagnostic;
using Mnemotron.Data.ClickHouse.Formats;
using Mnemotron.Data.ClickHouse.Json;
using Mnemotron.Data.ClickHouse.Types;
using Mnemotron.Data.ClickHouse.Utility;

namespace Mnemotron.Data.ClickHouse.ADO;

public class ClickHouseCommand : DbCommand, IClickHouseCommand, IDisposable
{
    private readonly CancellationTokenSource cts = new CancellationTokenSource();
    private readonly ClickHouseParameterCollection commandParameters = new ClickHouseParameterCollection();
    private Dictionary<string, object> customSettings;
    private ClickHouseConnection connection;

    public ClickHouseCommand()
    {
    }

    public ClickHouseCommand(ClickHouseConnection connection)
    {
        this.connection = connection;
    }

    public override string CommandText { get; set; }

    public override int CommandTimeout { get; set; }

    public override CommandType CommandType { get; set; }

    public override bool DesignTimeVisible { get; set; }

    public override UpdateRowSource UpdatedRowSource { get; set; }

    /// <summary>
    /// Gets or sets QueryId associated with command
    /// After query execution, will be set by value provided by server
    /// Value will be same if provided or a UUID generated by server if not
    /// </summary>
    public string QueryId { get; set; }

    public QueryStats QueryStats { get; private set; }

    /// <summary>
    /// Gets collection of custom settings which will be passed as URL query string parameters.
    /// </summary>
    /// <remarks>Not thread-safe.</remarks>
    public IDictionary<string, object> CustomSettings => customSettings ??= new Dictionary<string, object>();

    protected override DbConnection DbConnection
    {
        get => connection;
        set => connection = (ClickHouseConnection)value;
    }

    protected override DbParameterCollection DbParameterCollection => commandParameters;

    protected override DbTransaction DbTransaction { get; set; }

    public override void Cancel() => cts.Cancel();

    public override int ExecuteNonQuery() => ExecuteNonQueryAsync(cts.Token).GetAwaiter().GetResult();

    public override async Task<int> ExecuteNonQueryAsync(CancellationToken cancellationToken)
    {
        if (connection == null)
            throw new InvalidOperationException("Connection is not set");

        using var lcts = CancellationTokenSource.CreateLinkedTokenSource(cts.Token, cancellationToken);
        using var response = await PostSqlQueryAsync(CommandText, lcts.Token).ConfigureAwait(false);
#if NET5_0_OR_GREATER
        using var reader = new ExtendedBinaryReader(await response.Content.ReadAsStreamAsync(lcts.Token).ConfigureAwait(false));
#else
        using var reader = new ExtendedBinaryReader(await response.Content.ReadAsStreamAsync().ConfigureAwait(false));
#endif

        return reader.PeekChar() != -1 ? reader.Read7BitEncodedInt() : 0;
    }

    /// <summary>
    ///  Allows to return raw result from a query (with custom FORMAT)
    /// </summary>
    /// <param name="cancellationToken">Cancellation token</param>
    /// <returns>ClickHouseRawResult object containing response stream</returns>
    public async Task<ClickHouseRawResult> ExecuteRawResultAsync(CancellationToken cancellationToken)
    {
        if (connection == null)
            throw new InvalidOperationException("Connection is not set");

        using var lcts = CancellationTokenSource.CreateLinkedTokenSource(cts.Token, cancellationToken);
        var response = await PostSqlQueryAsync(CommandText, lcts.Token).ConfigureAwait(false);
        return new ClickHouseRawResult(response);
    }

    public override object ExecuteScalar() => ExecuteScalarAsync(cts.Token).GetAwaiter().GetResult();

    public override async Task<object> ExecuteScalarAsync(CancellationToken cancellationToken)
    {
        using var lcts = CancellationTokenSource.CreateLinkedTokenSource(cts.Token, cancellationToken);
        using var reader = await ExecuteDbDataReaderAsync(CommandBehavior.Default, lcts.Token).ConfigureAwait(false);
        return reader.Read() ? reader.GetValue(0) : null;
    }

    public override void Prepare() { /* ClickHouse has no notion of prepared statements */ }

    public new ClickHouseDbParameter CreateParameter() => new ClickHouseDbParameter();

    protected override DbParameter CreateDbParameter() => CreateParameter();

#pragma warning disable CA2215 // Dispose methods should call base class dispose
    protected override void Dispose(bool disposing)
#pragma warning restore CA2215 // Dispose methods should call base class dispose
    {
        if (disposing)
        {
            // Dispose token source but do not cancel
            cts.Dispose();
        }
    }

    protected override DbDataReader ExecuteDbDataReader(CommandBehavior behavior) => ExecuteDbDataReaderAsync(behavior, cts.Token).GetAwaiter().GetResult();

    protected override async Task<DbDataReader> ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
    {
        if (connection == null)
            throw new InvalidOperationException("Connection is not set");

        using var lcts = CancellationTokenSource.CreateLinkedTokenSource(cts.Token, cancellationToken);
        var sqlBuilder = new StringBuilder(CommandText);
        // CommandBehavior is a flags enum: SSDT's DSV wizard passes
        // SchemaOnly | KeyInfo, which a switch on the exact value silently
        // treats as Default — streaming the FULL table into a schema read.
        // Wrap in a subquery instead of appending: the command text may
        // already end with its own LIMIT (a second LIMIT is a syntax error).
        if (behavior.HasFlag(CommandBehavior.SchemaOnly))
            sqlBuilder = new StringBuilder($"SELECT * FROM ({CommandText}) LIMIT 0");
        else if (behavior.HasFlag(CommandBehavior.SingleRow))
            sqlBuilder = new StringBuilder($"SELECT * FROM ({CommandText}) LIMIT 1");
        var result = await PostSqlQueryAsync(sqlBuilder.ToString(), lcts.Token).ConfigureAwait(false);
        var reader = ClickHouseDataReader.FromHttpResponse(result, connection.TypeSettings);

        // ProbeStringLengths: on a metadata read, replace the flat DefaultStringSize
        // with the actual maximum length of each String column (one aggregate scan).
        if (behavior.HasFlag(CommandBehavior.SchemaOnly) && connection.ProbeStringLengths)
            reader.ProbedColumnSizes = await ProbeStringLengthsAsync(reader, lcts.Token).ConfigureAwait(false);

        return reader;
    }

    // Runs SELECT max(lengthUTF8(col)) over the original query for its String
    // columns (FixedString has a fixed declared length and is skipped; other
    // types report -1). lengthUTF8 = character count, matching DT_WSTR length;
    // ClickHouse max() ignores NULLs. Returns a per-ordinal size array or null.
    private async Task<int[]> ProbeStringLengthsAsync(ClickHouseDataReader reader, CancellationToken token)
    {
        var sizes = new int[reader.FieldCount];
        var projections = new List<string>();
        var ordinals = new List<int>();
        for (var i = 0; i < reader.FieldCount; i++)
        {
            sizes[i] = -1;
            var type = reader.GetClickHouseType(i);
            var inner = type is NullableType nt ? nt.UnderlyingType : type;
            if (inner is LowCardinalityType lc)
                inner = lc.UnderlyingType;
            if (inner is StringType)
            {
                ordinals.Add(i);
                projections.Add($"toInt64(max(lengthUTF8(`{reader.GetName(i).Replace("`", "``")}`)))");
            }
        }

        if (projections.Count == 0)
            return sizes;

        using var probe = new ClickHouseCommand(connection)
        {
            CommandText = $"SELECT {string.Join(", ", projections)} FROM ({CommandText})",
        };
        using var probeReader = (ClickHouseDataReader)await probe.ExecuteDbDataReaderAsync(CommandBehavior.Default, token).ConfigureAwait(false);
        if (await probeReader.ReadAsync(token).ConfigureAwait(false))
        {
            for (var j = 0; j < ordinals.Count; j++)
                sizes[ordinals[j]] = probeReader.IsDBNull(j) ? 0 : (int)Math.Min(int.MaxValue, Convert.ToInt64(probeReader.GetValue(j), CultureInfo.InvariantCulture));
        }

        return sizes;
    }

    private async Task<HttpResponseMessage> PostSqlQueryAsync(string sqlQuery, CancellationToken token)
    {
        if (connection == null)
            throw new InvalidOperationException("Connection not set");
        using var activity = connection.StartActivity("PostSqlQueryAsync");

        var uriBuilder = connection.CreateUriBuilder();
        await connection.EnsureOpenAsync().ConfigureAwait(false); // Preserve old behavior

        uriBuilder.QueryId = QueryId;
        uriBuilder.CommandQueryStringParameters = customSettings;

        var httpClient = connection.HttpClient;
        using var postMessage = connection.UseFormDataParameters
            ? BuildHttpRequestMessageWithFormData(
                sqlQuery: sqlQuery,
                uriBuilder: uriBuilder,
                httpClient: httpClient)
            : BuildHttpRequestMessageWithQueryParams(
                sqlQuery: sqlQuery,
                uriBuilder: uriBuilder,
                httpClient: httpClient);

        activity.SetQuery(sqlQuery);

        var response = await httpClient
            .SendAsync(postMessage, HttpCompletionOption.ResponseHeadersRead, token)
            .ConfigureAwait(false);

        QueryId = ExtractQueryId(response);
        QueryStats = ExtractQueryStats(response);
        activity.SetQueryStats(QueryStats);
        return await ClickHouseConnection.HandleError(response, sqlQuery, activity).ConfigureAwait(false);
    }

    private HttpRequestMessage BuildHttpRequestMessageWithQueryParams(string sqlQuery, ClickHouseUriBuilder uriBuilder, HttpClient httpClient)
    {
        if (commandParameters != null)
        {
            sqlQuery = commandParameters.ReplacePlaceholders(sqlQuery);
            foreach (ClickHouseDbParameter parameter in commandParameters)
            {
                uriBuilder.AddSqlQueryParameter(
                    parameter.ParameterName,
                    HttpParameterFormatter.Format(parameter, connection.TypeSettings));
            }
        }

        var uri = uriBuilder.ToString();

        var postMessage = new HttpRequestMessage(HttpMethod.Post, uri);

        connection.AddDefaultHttpHeaders(postMessage.Headers, httpClient);
        HttpContent content = new StringContent(sqlQuery);
        content.Headers.ContentType = new MediaTypeHeaderValue("text/sql");
        if (connection.UseCompression)
        {
            content = new CompressedContent(content, DecompressionMethods.GZip);
        }

        postMessage.Content = content;

        return postMessage;
    }

    private HttpRequestMessage BuildHttpRequestMessageWithFormData(string sqlQuery, ClickHouseUriBuilder uriBuilder, HttpClient httpClient)
    {
        var content = new MultipartFormDataContent();

        if (commandParameters != null)
        {
            sqlQuery = commandParameters.ReplacePlaceholders(sqlQuery);

            foreach (ClickHouseDbParameter parameter in commandParameters)
            {
                content.Add(
                    content: new StringContent(HttpParameterFormatter.Format(parameter, connection.TypeSettings)),
                    name: $"param_{parameter.ParameterName}");
            }
        }

        content.Add(
            content: new StringContent(sqlQuery),
            name: "query");

        var uri = uriBuilder.ToString();

        var postMessage = new HttpRequestMessage(HttpMethod.Post, uri);

        connection.AddDefaultHttpHeaders(postMessage.Headers, httpClient);

        postMessage.Content = content;

        return postMessage;
    }

    // Separate holder type so a broken ambient System.Text.Json (some VS/SSIS
    // hosts redirect it to an app-local ancient version — see TypeConverter)
    // can only fail summary parsing, never ClickHouseCommand's own type
    // initializer: a poisoned holder rethrows inside the try/catch below.
    private static class SummarySerializer
    {
        internal static readonly JsonSerializerOptions Options = new JsonSerializerOptions
        {
            PropertyNamingPolicy = new SnakeCaseNamingPolicy(),
            NumberHandling = System.Text.Json.Serialization.JsonNumberHandling.AllowReadingFromString,
        };
    }

    private static QueryStats ExtractQueryStats(HttpResponseMessage response)
    {
        try
        {
            const string summaryHeader = "X-ClickHouse-Summary";
            if (response.Headers.Contains(summaryHeader))
            {
                var value = response.Headers.GetValues(summaryHeader).FirstOrDefault();
                var jsonDoc = JsonDocument.Parse(value);
                return JsonSerializer.Deserialize<QueryStats>(value, SummarySerializer.Options);
            }
        }
        catch
        {
        }
        return null;
    }

    private static string ExtractQueryId(HttpResponseMessage response)
    {
        const string queryIdHeader = "X-ClickHouse-Query-Id";
        if (response.Headers.Contains(queryIdHeader))
            return response.Headers.GetValues(queryIdHeader).FirstOrDefault();
        else
            return null;
    }
}
